### ISSUE TITLE
[Feature Request] Scope filter for tool window

### ISSUE THREAD

**Issue by ymd45921** [lczerniawski/BetterComments-JetBrains#1]
Tool window in update 2.0.0 is quite useful, but search in entire project may be very slow for large codebase. TODO tool window embeded in Jetbrains IDE provided a scope selectbox which allows user to specific the scope to custom rules or presets like opened files, temp files and so on. I think the tool window will be more partical with this feature is implemented.

BTW, with the plugin enabled, comments with TODO begins will not appear in TODO tool window after 1.0.4 (but also not be highlighted like TODO supported by IDE). Is there any solution :)

**Comment by lczerniawski** [comment]
Hi! I'm glad you enjoyed it. 
I like the idea with the scope selector; I will try to implement that in the next few days. I agree with the search for the whole code being overkill; I didn't had an idea how to make it differently, so thanks.

Regarding the TODO highlight missing, it should be ok, as I didn't change any logic there, what IDE are you using then? I tried it on PyCharm and Intelji, and it looks good there.

**Comment by lczerniawski** [comment]
I pushed v2.1 with some scope filters.

**Comment by ymd45921** [comment]
Thanks for your work and merry Christmas!!!!

The IDE embeded TODO missing is seems work correctly in new version of the plugin. About this, I think it may be that the IDE itself is stuck when opening large project, causing the built-in TODO to not complete the search in time. It's all right now.
Thanks again for your work! It's really useful!
